module.exports = {
    //FCM token of the device generated by firebase on the client side, and message we want to send to the user
    //We need to save the tokens when the users login on their devices and then search for the users we want to send notifications to and then retrieve their tokens.
    sendNotificationByTopic(topic, msg) {
        return require('./sendNotification.js')(topic, msg);
    }
}